[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/Longlom/hello-world"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
